tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - GrammarCraft.xtend-lang@0.2.2:UtiWAatpxAnFrIDsJw5ZJA==
    - grammarcraft.xtext-lang@0.4.0:3zlywf5wuhQQzJdHR4VG1g==