/*
 * generated by Xtext 2.23.0
 */
package gol.tasks.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gol.tasks.TaskDSLRuntimeModule;
import gol.tasks.TaskDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TaskDSLIdeSetup extends TaskDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TaskDSLRuntimeModule(), new TaskDSLIdeModule()));
	}
	
}
