/*
 * generated by Xtext 2.23.0
 */
package game.life;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GoLDSLStandaloneSetup extends GoLDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new GoLDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
