/*
 * generated by Xtext 2.23.0
 */
package game.life.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import game.life.GoLDSLRuntimeModule;
import game.life.GoLDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GoLDSLIdeSetup extends GoLDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GoLDSLRuntimeModule(), new GoLDSLIdeModule()));
	}
	
}
